== Tutorial

The following tutorial walks you through creating and testing a control in the shared sandbox. 
You will create an authorization control that prevents users of your new card product from spending at liquor stores, which are represented by a single merchant category code.

If you want to test these controls after you create them, make sure to track the user and card product tokens you specify throughout the tutorial.

=== Step One: List existing controls

Before creating a new control, consider any existing controls you may have at the program and card product levels. 
To view existing authorization controls, send a request to the GET /authcontrols endpoint.

Make sure you understand your program's default authorization behavior (allow vs. deny). 
In the shared sandbox, the program's default behavior is set to globally allow transactions at all merchants.

=== Step Two: Design your controls

The business logic of the control you want to add determines the data you include in your request.

- To block spending at all liquor stores, include the merchant category code in the `merchant_scope` object.
- To apply the control to all users in your card product, include the card product token in the `association` object.

To avoid receiving an error, include all other necessary parameters.

- Create a meaningful name for the control: e.g. Deny Liquor Stores.
- Create a unique token for the control: e.g. deny_liquor_stores.

[NOTE]
Do not use the example tokens shown in the tutorial while working in the shared sandbox. 
If an object with the same token already exists, the system will handle the request as a duplicate, and your request will not take effect.

=== Step Three: Call the /authcontrols endpoint

The following code block provides a JSON-formatted sample message body for creating your control. 
Copy the code sample and paste it into the body field of the following widget. 
Replace any placeholder text (**UNIQUE TOKEN**, **CARD PRODUCT TOKEN**) with your sample data, then click *Submit Request*.
Review the response to ensure you successfully created the authorization control.

[source,json]
----
{
  "token": "**UNIQUE TOKEN**", 
  "name": "Deny Liquor Stores", 
  "association": { 
    "card_product_token": "**CARD PRODUCT TOKEN**" 
  }, 
  "merchant_scope": { 
    "mcc": "5921" 
  }, 
  "active": true 
}
----

Alternatively, you can use the following sample cURL to create the same control.

[source,curl]
----
curl \ 
-X POST \ 
--header 'Content-Type: application/json' \ 
--header 'Accept: application/json' \ 
--header 'Authorization: Basic **YOUR AUTHORIZATION STRING**' \ 
-d '{ 
  "token": "**UNIQUE TOKEN**", 
  "name": "Deny Liquor Stores", 
  "association": { 
    "card_product_token": "**CARD PRODUCT TOKEN**" 
  }, 
  "merchant_scope": { 
    "mcc": "5921" 
  }, 
  "active": true 
}' \ 
'https://shared-sandbox-api.marqeta.com/v3/authcontrols'
----

=== Step Four: Confirm the new control exists

To confirm that you created the control, call the GET /authcontrols endpoint using the card product token you used previously. 
Replace any placeholder text (**CARD PRODUCT TOKEN**) with your sample data. Your new control should be included in the returned list.

[source,curl]
----
https://shared-sandbox-api.marqeta.com/v3/authcontrols?card_product=**CARD PRODUCT TOKEN**&count=5&sort_by=-lastModifiedTime
----

=== Step Five: Call the /simulate endpoint

To test if the control functions properly, simulate an authorization transaction using the `POST /simulate/authorization` endpoint. 
Test several transactions that each force the Marqeta platform to allow or deny them.

The following sample message body creates a transaction that the Marqeta platform denies because of the authorization control created in the tutorial. 
Replace any placeholder text (**YOUR CARD TOKEN**) with your sample data. 
Change the MCC and resubmit the request to simulate a transaction that Marqeta allows.

[source,json]
----
{ 
  "amount": "100", 
  "mid": "12345", 
  "card_token": "**YOUR CARD TOKEN**", 
  "card_acceptor": { 
    "mcc":"5921" 
  } 
}
----

[NOTE]
When testing controls in the shared sandbox, keep in mind that controls created by other sandbox users might impact your testing. If the transaction result is unexpected, check the response body for details on what went wrong.