ignorefiles = [ "snippets", "api", "topics", "tutorials" ]

baseURL = "https://codeforspace.github.io/"
languageCode = "en-us"
title = "Marqeta Developers"

theme = "hugo-theme-learn"

[outputs]
home = [ "HTML", "RSS", "JSON"]
