== Configuring AVS behaviors

The Marqeta platform defines AVS behaviors at the card product level.
AVS match determinations are enabled by default for the following types of transactions:

- Authorization messages.
- Account verification messages.
- Digital wallet token activation requests.

You can disable AVS match determinations for one transaction type, such as authorizations, while enabling it for another, such as account verification messages.

If AVS is enabled for authorization or account verification messages, you can configure the following AVS behaviors, which occur in addition to making the match determination:

- Decline the transaction based on a mismatched street address (disabled by default).
- Decline the transaction based on a mismatched postal code (enabled by default).

For example, you can configure AVS to decline authorizations based on a mismatched street address but allow authorizations with a mismatched postal code.

The Marqeta platform does not decline digital wallet token activation requests based on AVS mismatches.
Instead, the Marqeta platform returns a "Not declined" response to the network, which triggers a request for further verification before provisioning a digital wallet token.
See Managing the Lifecycle of Digital Wallet Tokens for more information on additional verification options.

[NOTE]
To review your card product's AVS configuration, issue a `GET` to `/cardproducts/{token}` using your card product's token as the path parameter. For a complete description of the `/cardproducts` endpoint, see Card Products.