== The card lifecycle

From issuance to expiration, cards transition (or switch) between several states during their lifetime. 
The following endpoints enable you to manipulate a card's state:

To issue a new card or reissue an existing card, use the `/cards` endpoint.
To transition a card between states, use the `/cardtransitions` endpoint.

[NOTE]
In addition to your API calls, Marqeta and the card holder can affect the state of a card.

The following diagram outlines the possible transitions between states.

=== Issuance and reissuance

When issuing a card, you can choose to create an original card or to reissue an existing card. 
A reissued card behaves the same and has the same card number as the source card. 
For example, if a card has expired, you can reissue the card with the same PAN and a new expiration date.

You can only reissue a source card once; the source card can be an original card or a reissued card. 
For example, you might create an original-issue Card A, then reissue Card A as Card B, and then reissue Card B as Card C, resulting in a reissue chain that looks like this: "Card A > Card B > Card C".

You can also configure whether the original card is automatically terminated or remains active when reissued, though this is limited by your program's maximum active card limit. 
Contact a Marqeta Customer Success representative to determine how many active cards your users can own.

[NOTE]
All digital wallet tokens associated with a reissued card are reassigned to the new card when it's activated.

=== Activation

Cards must be activated before use. You can configure your card product so that new cards are active upon issuance. 
In general, new physical cards are shipped in an unactivated state, while new virtual cards are digitally presented (shown on a screen, for example) and active immediately.

Activating an original-issue card (as opposed to a reissued card) never affects other cards owned by the user. 
An error is returned if any attempted activation would result in the user owning more active and/or suspended cards than the maximum allowed by the program configuration.

If you issue unactivated cards, you must provide your card holders a method for activating them. 
The method you choose depends on your implementation and data security compliance requirements.

Available methods for activating cards include:

- An iframe widget that injects a card activation tool into your webpage or web application.
- Over the phone, using an interactive voice response (IVR) system.
- The `/cardtransitions` endpoint of the Core API.

=== Suspension and termination

To make a card temporarily nonfunctional, you can suspend it. 
Suspended cards can transition back to the active state.

To make a card permanently nonfunctional, you can transition it to the TERMINATED state. 
Terminated cards cannot be reactivated.

[NOTE]
Clearing and refund events will succeed for suspended and terminated cards.

=== Expiration

When you create a new card, the Marqeta platform assigns an expiration date and time. 
When the expiration time is reached, the card is terminated automatically. 
You can set the expiration date for a card product or an individual card.

=== Lost, stolen, or damaged cards

When a card holder is separated from their card or it becomes physically nonfunctional, you should take action to limit potential fraud and provide the user a functional card.

In general, you should respond to card problems in the following ways:

- If a card is lost, you should suspend or terminate the card and reissue it with a new PAN.
- If a card is stolen, you should terminate the card and reissue it with a new PAN.
- If a card is damaged, you should terminate the card and reissue it with the same PAN.

[NOTE]
For more information, see Managing Lost, Stolen, or Damaged Cards page.

