== Cards in the payments ecosystem

In the payments ecosystem, a card stores data necessary for a merchant to make an authorization request.
The card holder presents the card to the merchant at a physical point of sale or enters the information into a form for an online purchase.
When the merchant has the card data, they can attempt to complete the transaction.

Cards store multiple pieces of data necessary to complete a transaction, including the following:

- *Name* – card holder's name.
- *Primary account number (PAN)* – unique identifier that appears on the front of the card; identifies the card network, issuing bank, and card holder account.
- *Expiration date* – date when the card expires.
- *Card verification value (CVV2)* – verification number that appears on the back of the card, usually used for “card not present” transactions. Some card networks refer to this as the *card verification code (CVC)*.

Some cards, including EMV "chip and PIN" cards, also require a *personal identification number (PIN)*. You can also choose to enable the PIN feature, whether it is required or not. If a PIN is required or you opt to enable it, you must provide the card holder a method of setting the PIN. Available methods include the following:

- An iframe widget that injects a PIN-setting tool into your webpage or web application.
- Over the phone, using an interactive voice response (IVR) system.
- The `/pins` endpoint of the Marqeta platform.

[NOTE]
Funds are not loaded onto or directly associated with a card.
Rather, a card is a device used to access funds held in a user or business account.

=== Form factors

You can issue cards in the following form factors:

[cols="1,3,3", options="header"]
|===
|Form factor
|Description
|Scenario

|Physical
|A traditional plastic card, ordered through a third-party provider, shipped to the address provided.
|Making payments at physical points of sale.

For example, you can issue a physical card to enable a delivery service to make any necessary purchases at retailers.

|Virtual
|A virtual payment card with no physical component.
|A card intended for immediate use.

For example, you can issue a virtual card to make a payment to a retailer after the user signs up for an alternative lending payment plan. The lender can add the necessary funds to an account and create a new one-time-use virtual card to provide payment to the retailer.
|===

You can also provision digital wallet tokens for use in digital wallets like Apple Pay and Google Pay. 
Digital wallets enable users to make in-store and online payments using any device storing their tokenized card. 
Each token is based on an existing physical or virtual card. 
For more information on tokenization and digital wallets, see Digital Wallets and Tokenization.

=== Single- vs. multi-use cards

You can configure a card to be usable once or multiple times.

- A single-use card only functions for one transaction, after which the Marqeta platform terminates the card.
- A multi-use card functions for multiple transactions, usually until the expiration date is reached.

[NOTE]
You can create a single-use card by applying a velocity control. A velocity control specifies how much and how frequently a user can spend their funds. For more information on setting up a single-use card, see the Controlling Spending page.

=== Number of cards

You can set the number of active or suspended cards each user can own. 
The following card ownership scenarios are possible:

- Each user can own a single active or suspended card.
- Each user can own multiple active or suspended cards that share the same PAN (by reissuing an existing card).
- Each user can own multiple active or suspended cards with one or more PANs (by issuing original cards or reissuing existing cards).

For information on creating original cards and reissuing existing cards, see <<Issuance and reissuance>>.