=== Controls to limit where users can spend

To limit where users can spend funds, use *authorization controls*. Authorization controls allow you to pick the merchants where users can (or cannot) spend their funds.

In the API request, the `merchant_scope` object defines the merchant or group of merchants affected by the authorization control. The object requires one (and only one) of the following identifiers:

- Merchant ID – A unique identifier for a single merchant.
Merchant Category Code (MCC) – A unique identifier for a type of goods or services provided by a set of merchants.
- MCC Group – A unique identifier for a group of merchant category codes.

Your program's default authorization behavior can block all merchants by default, requiring you to whitelist allowable merchants, or it can allow all merchants by default, requiring you to blacklist blocked merchants. 
Make sure you know your program's default behavior before designing your controls. 
There is no distinction between a control that allows or blocks merchants—it is an exception to your program's default behavior. 
For example, a control that includes the MCC for hotels (7011) in the merchant_scope object would block hotels under the blacklist default behavior, but would allow hotels under the whitelist default behavior.

You can optionally configure start and end dates for your control to limit spending at merchants for predetermined periods of time. 
For example, a rewards card might limit a user's ability to spend outside of specific promotional periods.