=== Controls at transaction time

When a user attempts to spend with a card, the Marqeta platform evaluates the transaction against all controls applied to that user, including controls applied at the program and card product levels. 
If the details of the transaction violate any of the controls, the transaction fails.

The following transactions do not apply to the limits defined in a velocity control:

- Declined authorizations
- Account verification authorizations

The effects of all velocity controls are user-specific. 
If a card product has a velocity control limiting users to $100 of spending each day, then each associated user can spend $100. 
They are not impacted by the spending of other users, even if they share a parent account.

If a user owns multiple cards, spend controls apply in the following ways:

- If a user has multiple cards associated with the same card product, then spending on any of those cards counts toward any velocity controls applied to that card product. 
In other words, all of the user’s cards share the card product's velocity control.
- If a user has multiple cards associated with different card products, then spending on a card only counts toward velocity controls applied to its card product. 
In other words, spending on a card associated with Card Product A does not affect the limits of a card associated with Card Product B. 
- A velocity control applied to a user always affects all of the user's cards.

For more information about how many cards a user can own, see About Cards.

[NOTE]
When using a card funded using Just-in-Time (JIT) Funding, every spend event has a matching load event that returns the account balance to zero. 
Load controls operate similarly to spend controls—they limit the amount and frequency of funds that can be added to an account. 
To understand the load controls applied to your program, contact your Marqeta Customer Success representative. 
To learn more about JIT Funding, see About Just-in-Time Funding.
