+++
title = "Quick Start"
weight = 10
categories = ["Getting Started"]
+++
// This doesn't show up, does it?

= Quick Start
:toc: 
:toc-title:

Marqeta provides its customers with a sandbox environment in order to aquaint them with the Marqeta API. 
The sandbox allows customers to create the objects required to conduct financial transactions and to then simulate transactions using those objects.

include::content/snippets/note_contact_support.adoc[]

This page walks you through the simplest and most basic setup that allows for simulating transactions.
In brief, you will learn how to access the sandbox, create four objects (a card product, a funding source, a user, and a card), fund the user's account, and then simulate a transaction.
(Note that in this example, you explicitly pre-fund the user's account before simulating a transaction.
In a more complex scenario, you might choose instead to employ Just-In-Time Funding, whereby funds for the transaction amount are automatically loaded into the user's account at transaction time.)

This page also instructs customers on how to configure the sandbox environment to send webhook notifications in response to transaction events.

[#basic-concepts]
== Basic concepts

The fundamental purpose of the Marqeta API is to issue payment cards and customize card behavior.
In a production environment, cards are used to pay merchants for goods and services.
When such a purchase occurs, the transaction is routed over a payment card network to Marqeta for approval.
However, because the sandbox environment is not connected to an actual payment card network, transactions are simulated.

The API uses objects to represent various concepts.
For example, a payment card is represented by a `card` object and a card holder is represented by a `user` object.
You create a new object, such as a `card` or `user`, by making a call to the appropriate API endpoint.

A `card` is an example of a first-class object, in which the object name occupies the first node in the endpoint URL (in this case, `/cards`).
First-class objects are generally the most important objects on the Marqeta platform.
They include `cards`, `users`, `gpaorders` (used to load funds into a user account), and `fundingsources` (the source of funds from which a `gpaorder` draws).
Refer to the Summary of Resources to see how the most fundamental API objects interrelate.

The Marqeta API is RESTful, meaning that it uses HTTP verbs (`POST`, `PUT`, `GET`) to perform functions on objects.
Specifically, `POST` is used to create an object, `PUT` to update an object, and `GET` to retrieve an object.
For example, to create a new user object you would send a `POST` request to `/users`.

`POST` and `PUT` requests usually require you to pass data in the message body to define the attributes of the object being created or updated.
This data must be in JSON format.