+++
title = "About Address Verification"
categories = ["Cards"]
tags = ["Cards", "AVS", "Identity Verification"]
weight = 200
myThing = "AVS"
+++

= About Address Verification
:topicdir: content/topics/cards
:toc: 
:toc-title:

The *Address Verification System (AVS)* compares purchaser-provided address data against card holder address data held on file by the Marqeta platform and makes a match determination.
You can configure AVS to decline transactions programmatically based on a mismatched street address or postal code.

AVS is useful for card-not-present environments, such as e-commerce websites, and points of sale without clerks, such as automated fuel dispensers—wherever there is additional need to verify that the person making the purchase is the legitimate card holder.

At the end of the guide, you should understand:

- How AVS makes a match determination.
- The role of AVS in the transaction lifecycle.
- How the Marqeta platform records AVS decisions.
- How AVS affects transactions using Just-in-Time (JIT) Funding.

include::{topicdir}/avs_match_determinations.adoc[]

include::{topicdir}/avs_configuring_behaviors.adoc[]