+++
title = "Controlling Spending"
categories = ["Cards"]
tags = ["Spend controls", "Cards"]
+++

= Controlling Spending
:outfilesuffix: /
:toc: 
:toc-title:
:toclevels: 1
:topicdir: content/topics/cards

The Marqeta platform enables you to create controls for limiting user spending. 
A user represents the card holder to whom one or more cards may be associated. 
You can apply spending controls to one or more users. 
Use multiple controls to create robust rules for your users.

You can control a user's spending based on:

- Where the user spends (individual merchants or merchant categories).
- How much the user spends (transaction amount and frequency of spending in a given time period).
- How much the user spends at a specific merchant or category of merchants.

The platform also allows you to update and list existing controls. For a complete description of the `/authcontrols` endpoint, see the Authorization Controls page. For a complete description of the `/velocitycontrols` endpoint, see the Velocity Controls page.

At the end of the guide, you should understand:

- How to create new spend controls (authorization and velocity controls).
- How controls are applied at the program, card product, and user levels.
- How controls are evaluated at transaction time.

== Prerequisites

- Read the <</guides/getting_started/quick_start.adoc#_quick_start, Quick Start>> guide.
- Obtain a card product token and a token for an active card that is associated with that card product.

== Concepts

include::{topicdir}/spend_controls_levels_of_control.adoc[]

include::{topicdir}/spend_controls_auth_controls.adoc[]

include::{topicdir}/spend_controls_velocity_controls.adoc[]

=== Authorization controls vs. velocity controls
Authorization and velocity controls share some attributes and behaviors, but they serve distinct purposes.

- Authorization controls block (or allow) transactions at one or more merchants, regardless of the amount or frequency of spending. 
For example, you can block your users from spending at a grocery store for all time or block them for a specific period of time, but you can't limit the spending amount within that time period using an authorization control.
- Velocity controls limit transactions at one or more merchants based on a velocity window. 
For example, you can limit spending at grocery stores to a maximum of $100 each week.

include::{topicdir}/spend_controls_at_transaction_time.adoc[]

include::content/tutorials/create_a_spend_control.adoc[]

== Samples

Use the following samples to help build your program's spend controls. Each sample includes a description of the use case and sample JSON and cURL code snippets.

=== Allow user spending at a single merchant

You can limit a user's spending to a single merchant. 
This is handy if you are creating a rewards card that should only be used at a specific retailer or service. 
(Depending on your program's default authorization behavior, the same control could be used to block spending at a single merchant.)

[source,json]
{ 
  "token": "**UNIQUE TOKEN**", 
  "name": "Only Dunkin Donuts", 
  "association": { 
    "user_token": "**USER TOKEN REQUIRED**" 
  }, 
  "merchant_scope": { 
    "mid": "252824676910001" 
  }, 
  "active": true 
}

[source,curl]
curl \
-X POST \ 
--header 'Content-Type: application/json' \ 
--header 'Accept: application/json' \ 
--header 'Authorization: Basic **YOUR AUTHORIZATION STRING**' \ 
-d '{ 
  "token": "**UNIQUE TOKEN**", 
  "name": "Only Dunkin Donuts", 
  "association": { 
    "user_token": "**USER TOKEN REQUIRED**" 
  }, 
  "merchant_scope": { 
    "mid": "252824676910001" 
  }, 
  "active": true 
}' \ 
'https://shared-sandbox-api.marqeta.com/v3/authcontrols'

=== Limit spending to $100 per day

Using a velocity control, you can cap the amount a user spends in a given timeframe. 
If, for example, you know your card holders shouldn't spend more than $100 per day, you could use a velocity control to deny any transactions beyond that limit.

[source,json]
{ 
  "token": "**UNIQUE TOKEN**", 
  "name": "100 Daily Spend Limit", 
  "association": { 
    "user_token": "**USER TOKEN**" 
  }, 
  "usage_limit": 100, 
  "currency_code": "USD", 
  "amount_limit": 100, 
  "velocity_window": "DAY", 
  "active": true 
}

[source,curl]
curl \ 
-X POST \ 
--header 'Content-Type: application/json' \ 
--header 'Accept: application/json' \ 
--header 'Authorization: Basic **YOUR AUTHORIZATION STRING**' \ 
-d '{ 
  "token": "**UNIQUE TOKEN**", 
  "name": "100 Daily Spend Limit", 
  "association": { 
    "user_token": "**USER TOKEN**" 
  }, 
  "usage_limit": 100, 
  "currency_code": "USD", 
  "amount_limit": 100, 
  "velocity_window": "DAY", 
  "active": true 
}' \ 
'https://shared-sandbox-api.marqeta.com/v3/velocitycontrols'

=== Limit spending to $100 per transaction

You can limit a user's per-transaction spending by creating a velocity control with the `velocity_window` field set to TRANSACTION.

[source,json]
{ 
  "token": "**UNIQUE TOKEN**", 
  "name": "100 Per Transaction Limit", 
  "association": { 
    "user_token": "**USER TOKEN**" 
  }, 
  "currency_code": "USD", 
  "amount_limit": 100, 
  "velocity_window": "TRANSACTION", 
  "active": true 
}

[source,curl]
curl \ 
-X POST \ 
--header 'Content-Type: application/json' \ 
--header 'Accept: application/json' \ 
--header 'Authorization: Basic **YOUR AUTHORIZATION STRING**' \ 
-d '{ 
  "token": "**UNIQUE TOKEN**", 
  "name": "100 Per Transaction Limit", 
  "association": { 
    "user_token": "**USER TOKEN**" 
  }, 
  "currency_code": "USD", 
  "amount_limit": 100, 
  "velocity_window": "TRANSACTION", 
  "active": true 
}' \ 
'https://shared-sandbox-api.marqeta.com/v3/velocitycontrols'

=== Limit users to one transaction per week at a category of merchants

You can limit a user's maximum number of transactions for a given time period. 
For example, you can create a limited-use card product that prevents users from spending too frequently at a given merchant or category of merchants, such as hotels and motels. 
This is handy if you know how frequently a card holder should be spending with their card.

[source,json]
{ 
  "token": "**UNIQUE TOKEN**", 
  "name": "One Transaction Per Week at Hotels", 
  "association": { 
    "card_product_token": "**CARD PRODUCT TOKEN REQUIRED**" 
  }, 
  "merchant_scope": { 
    "mcc": "7011" 
  }, 
  "usage_limit": "1", 
  "currency_code": "USD", 
  "amount_limit": 1000, 
  "velocity_window": "WEEK", 
  "active": true 
}

[source,curl]
curl \ 
-X POST \ 
--header 'Content-Type: application/json' \ 
--header 'Accept: application/json' \ 
--header 'Authorization: Basic **YOUR AUTHORIZATION STRING**' \ 
-d '{ 
  "token": "**UNIQUE TOKEN**", 
  "name": "One Transaction Per Week At Hotels", 
  "association": { 
    "card_product_token": "**CARD PRODUCT TOKEN REQUIRED**" 
  }, 
  "merchant_scope": { "mcc": "7011" }, 
  "usage_limit": 1, 
  "currency_code": "USD", 
  "amount_limit": 1000, 
  "velocity_window": "WEEK", 
  "active": true 
}' \ 
'https://shared-sandbox-api.marqeta.com/v3/velocitycontrols'

=== Limit users to a single purchase

You can add a velocity control that allows a user to spend exactly once. 
By setting the usage limit to one (a single transaction) and the velocity window to lifetime, users can spend up to the amount limit once. 
Any future attempts to spend are blocked.

[source,json]
{
  "token": "**UNIQUE TOKEN**", 
  "name": "Single Use Card",
  "association": {
    "card_product_token": "**CARD PRODUCT TOKEN REQUIRED**"
  },
  "usage_limit": 1, 
  "currency_code": "USD", 
  "amount_limit": 1000,
  "velocity_window": "LIFETIME",
  "active": true 
}

[source,curl]
curl \ 
-X POST \ 
--header 'Content-Type: application/json' \ 
--header 'Accept: application/json' \ 
--header 'Authorization: Basic **YOUR AUTHORIZATION STRING**' \ 
-d '{
  "token": "**UNIQUE TOKEN**",    
  "name": "Single Use Card",    
  "association": {      
    "card_product_token": "**CARD PRODUCT TOKEN**"    
  },    
  "usage_limit": 1,    
  "currency_code": "USD",    
  "amount_limit": 1000,    
  "velocity_window": "LIFETIME",    
  "active": true  
}' \ 
'https://shared-sandbox-api.marqeta.com/v3/velocitycontrols'

=== Limit ATM withdrawals and bank transfers

You can create a velocity control to limit the funds users can withdraw from ATMs or transfer from a bank. 
By setting the spending limit for ATMs and bank transfers to $0, the user can only make retail purchases.

[source,json]
{ 
  "token": "**UNIQUE TOKEN**", 
  "name": "No ATMS or Bank Transfers", 
  "association": { 
    "user_token": "**USER TOKEN REQUIRED**" 
  }, 
  "usage_limit": 100, 
  "approvals_only": true, 
  "include_purchases": false, 
  "include_cashbacks": false,
  "include_withdrawals": true, 
  "include_transfers": true, 
  "currency_code": "USD", 
  "amount_limit": 0, 
  "velocity_window": "MONTH", 
  "active": true 
}

[source,curl]
curl \ 
-X POST \ 
--header 'Content-Type: application/json' \ 
--header 'Accept: application/json' \ 
--header 'Authorization: Basic **YOUR AUTHORIZATION STRING**' \ 
-d '{ 
  "token": "**UNIQUE TOKEN**", 
  "name": "No ATMS or Bank Transfers", 
  "association": { 
    "user_token": "**USER TOKEN**" 
  }, "usage_limit": 100, 
  "approvals_only": true, 
  "include_purchases": false, 
  "include_cashbacks": false,
  "include_withdrawals": true, 
  "include_transfers": true, 
  "currency_code": "USD", 
  "amount_limit": 0, 
  "velocity_window": "MONTH", 
  "active": true 
}' \ 
'https://shared-sandbox-api.marqeta.com/v3/velocitycontrols'

=== List all velocity controls for a single user

You can retrieve a list of all velocity controls applied at the program level, or use a query parameter to filter the list of controls by user or card product.

[source,curl]
https://shared-sandbox-api.marqeta.com/v3/velocitycontrols?user=**USER TOKEN REQUIRED**

[source,curl]
curl \
-X GET \
--header 'Accept: application/json' \
--header 'Authorization: Basic **YOUR AUTHORIZATION STRING**' \
'https://shared-sandbox-api.marqeta.com/v3/velocitycontrols?user=**USER TOKEN REQUIRED**'