+++
title = "Cards"
tags = ["Cards"]
+++

= Cards
:toc:
:toc-title:
:toclevels: 1
:outfilesuffix: /

Use this view endpoint to retrieve card state and history data aggregated by card. 
The data is derived from card information in the Marqeta platform.

This endpoint supports multiple response formats, query filtering, field filtering, sorting, and pagination. 
For more information about response options, see <</diva/basics/response_customization.adoc#_response_customization, Response Customization>>.

== Retrieve card data (JSON)

*Action:* `GET` +
*Endpoint:* `/views/cards/detail`

Retrieve card state and history data aggregated by card. 
This endpoint returns a JSON object that contains an array of records matching your filter query.

=== Sample response body

The following sample shows a representative response for a `GET` request to the `/views/cards/detail?program=my_program&fields=card_created_date,card_activation_date, card_state,card_type&card_created_date=2017-09-01..2017-09-30` endpoint.

[source,json]
{
     "total": 47067,
     "is_more": true,
     "count": 10000,
     "info": {},
     "start_date": "2017-09-01T15:13:53+0000",
     "end_date": "2017-09-30T23:58:16+0000",
     "last_run_time": "2018-03-09T10:03:22Z",
    "schema": [
        {
            "field": "card_created_date",
            "type": "date",
            "display": "Card Created Date",
            "units": null,
            "hasTotal": false,
            "date_format": "YYYY-MM-DD HH:mm:ss",
            "is_filter_only": false
        },
        {
            "field": "card_activation_date",
            "type": "date",
            "display": "Card Activation Date",
            "units": null,
            "hasTotal": false,
            "date_format": "YYYY-MM-DD HH:mm:ss",
            "is_filter_only": false
        },
        {
            "field": "card_state",
            "type": "character varying(128)",
            "display": "Card State",
            "enum_values": [],
            "units": null,
            "hasTotal": false,
            "is_filter_only": false
        },
        {
            "field": "card_type",
            "type": "character varying(128)",
            "display": "Card Type",
            "enum_values": [],
            "units": null,
            "hasTotal": false,
            "is_filter_only": false
        }
    ],
     "records": [
         {
             "card_created_date": "2017-09-30T20:32:19.000Z",
             "card_activation_date": "2017-09-30T00:00:00.000Z",
             "card_state": "ACTIVE",
             "card_type": "Virtual",
         },
         …
     ]
 }


== Retrieve card data (file export)

*Action:* `GET` +
*Endpoint:* `/views/cards/detail/{export_type}`

Retrieve card state and history data aggregated by card. 
This endpoint asynchronously generates a file in the specified format and returns a job token for retrieving the file when it is completed. 
The file contains a list of records matching your filter query.