+++
title = "Users"
tags = ["Users"]
+++

= Users
:toc:
:toc-title:
:toclevels: 1
:outfilesuffix: /

Use this view endpoint to retrieve user data aggregated by user. 
The data is derived from user information in the Marqeta platform.

This endpoint supports multiple response formats, query filtering, field filtering, sorting, and pagination. 
For more information about response options, see <</diva/basics/response_customization.adoc#_response_customization, Response Customization>>.

== Retrieve user data (JSON)

*Action:* `GET` +
*Endpoint:* `/views/users/detail`

Retrieve user data aggregated by user. 
This endpoint returns a JSON object that contains an array of records matching your filter query.

=== Sample response body

The following sample shows a representative response for a GET request to the `/views/users/detail?program=my_program` endpoint.

[source,json]
{
    "total": 4,
    "is_more": false,
    "count": 4,
    "info": {},
    "start_date": "2015-06-12T00:39:44+0000",
    "end_date": "2018-02-14T01:33:19+0000",
    "last_run_time": "2018-03-09T10:04:32Z",
    "schema": [
        {
            "field": "user_token",
            "type": "character varying(128)",
            "display": "User Token",
            "units": null,
            "hasTotal": false,
            "is_filter_only": false
        },
        {
            "field": "user_created_date",
            "type": "timestamp without time zone",
            "display": "User Created Date",
            "units": null,
            "hasTotal": false,
            "date_format": "YYYY-MM-DD HH:mm:ss",
            "is_filter_only": false
        },
        {
            "field": "account_type",
            "type": "character varying(128)",
            "display": "Account Type",
            "units": null,
            "hasTotal": false,
            "is_filter_only": false
        },
        {
            "field": "city",
            "type": "character varying(128)",
            "display": "City",
            "units": null,
            "hasTotal": false,
            "is_filter_only": false
        },
        {
            "field": "state",
            "type": "character varying(128)",
            "display": "State",
            "units": null,
            "hasTotal": false,
            "is_filter_only": false
        },
        {
            "field": "zip",
            "type": "character varying(128)",
            "display": "Zip",
            "units": null,
            "hasTotal": false,
            "is_filter_only": false
        },
        {
            "field": "country",
            "type": "character varying(128)",
            "display": "Country",
            "units": null,
            "hasTotal": false,
            "is_filter_only": false
        },
        {
            "field": "parent_user_token",
            "type": "character varying(128)",
            "display": "Parent User Token",
            "units": null,
            "hasTotal": false,
            "is_filter_only": false
        },
        {
            "field": "active_status",
            "type": "character varying(3)",
            "display": "Active Status",
            "units": null,
            "hasTotal": false,
            "is_filter_only": false
        }
    ],
    "records": [
        {
            "user_token": "f50b74c3-92c2-47e4-9e1e-30eadab1a982",
            "user_created_date": "2018-02-14T01:33:19.000Z",
            "account_type": "Parent",
            "city": "Parkerville",
            "state": "CA",
            "zip": "94612",
            "country": "United States",
            "parent_user_token": "f50b74c3-92c2-47e4-9e1e-30eadab1a982",
            "active_status": "Y"
        },
        {
            "user_token": "55555544-8d2c-4a11-be65-97baf5c84336",
            "user_created_date": "2015-07-24T19:16:14.000Z",
            "account_type": "Parent",
            "city": "Emeryville",
            "state": "CA",
            "zip": "94608",
            "country": "United States",
            "parent_user_token": "55555544-8d2c-4a11-be65-97baf5c84336",
            "active_status": "Y"
        },
        {
            "user_token": "665e2627-683f-44ba-bb0a-e93ebe457680",
            "user_created_date": "2015-06-12T18:07:52.000Z",
            "account_type": "Parent",
            "city": "Emeryville",
            "state": "CA",
            "zip": "94608",
            "country": "United States",
            "parent_user_token": "665e2627-683f-44ba-bb0a-e93ebe457680",
            "active_status": "Y"
        },
        {
            "user_token": "3b2de7df-708c-4857-86b9-3c5eab7aed38",
            "user_created_date": "2015-06-12T00:39:44.000Z",
            "account_type": "Parent",
            "city": "Emeryville",
            "state": "CA",
            "zip": "94608",
            "country": "United States",
            "parent_user_token": "3b2de7df-708c-4857-86b9-3c5eab7aed38",
            "active_status": "N"
        }
    ]
}

== Retrieve user data (file export)

*Action:* `GET` +
*Endpoint:* `/views/users/detail/{export_type}`

Retrieve user data aggregated by user. 
This endpoint asynchronously generates a file in the specified format and returns a job token for retrieving the file when it is completed. 
The file contains a list of records matching your filter query.