name: Build w/ Hugo & deploy to GitHub Pages

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - run: npm ci

      - name: Build
        run: docker run --rm --volume $PWD:/src -w "/src" bwklein/hugo-asciidoctor ./build.sh

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          # or github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: master
          publish_dir: ./public
